# Generated by Django 6.0.4 on 2026-04-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('top', 'Top'), ('middle', 'Middle'), ('base', 'Base')], default='N/A', max_length=10),
        ),
    ]
