# Generated by Django 6.0.4 on 2026-04-19 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_notes_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='type',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='notes',
        ),
        migrations.CreateModel(
            name='PerfumeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N/A', 'N/A'), ('top', 'Top'), ('middle', 'Middle'), ('base', 'Base')], default='N/A', max_length=10)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.notes')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.perfume')),
            ],
        ),
        migrations.AddField(
            model_name='perfume',
            name='note',
            field=models.ManyToManyField(blank=True, through='product.PerfumeNote', to='product.notes'),
        ),
    ]
