# Generated by Django 6.0.4 on 2026-04-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_notes_type_remove_perfume_notes_perfumenote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
