# Generated by Django 6.0.4 on 2026-04-19 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_notes_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='image',
        ),
        migrations.CreateModel(
            name='PerfumeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='perfume_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.perfume')),
            ],
        ),
    ]
