# Generated by Django 6.0.4 on 2026-04-19 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_perfume_image_perfumeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfume',
            name='is_restocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfume',
            name='is_seasonal_pick',
            field=models.BooleanField(default=False),
        ),
    ]
