# Generated by Django 6.0.4 on 2026-04-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_perfume_date_added_perfume_is_restocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumeimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
