# Generated by Django 6.0.4 on 2026-04-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_perfumeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
