# Generated by Django 6.0.4 on 2026-04-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_perfume_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='perfume',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
