# Generated by Django 6.0.4 on 2026-04-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_perfume_gender_perfume_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
