# Generated by Django 6.0.4 on 2026-04-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_perfume_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumeimage',
            name='image',
            field=models.ImageField(upload_to='perfume_images/'),
        ),
    ]
