# Generated by Django 6.0.4 on 2026-04-27 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_perfumeimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atomizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='perfume',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='family',
            field=models.ManyToManyField(to='product.family'),
        ),
        migrations.CreateModel(
            name='Decant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.perfume')),
            ],
        ),
    ]
