# Generated by Django 6.0.4 on 2026-04-28 04:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_atomizer_perfume_stock_alter_perfume_family_decant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Longevity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24)])),
                ('perfume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='longevity', to='product.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='Sillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('perfume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sillage', to='product.perfume')),
            ],
        ),
    ]
