# Generated by Django 6.0.4 on 2026-04-29 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_longevity_sillage'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='type',
            field=models.CharField(choices=[('Attar', 'attar'), ('Perfume', 'perfume')], default='perfume', max_length=20),
        ),
        migrations.AlterField(
            model_name='longevity',
            name='level',
            field=models.PositiveIntegerField(default=0, help_text='Enter a value from 0 to 24, representing the number of hours the perfume lasts.', validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='sillage',
            name='level',
            field=models.PositiveIntegerField(default=0, help_text='Enter a value from 0 to 10, where 0 means no sillage and 10 means very strong sillage.', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
