# Generated by Django 6.0.4 on 2026-04-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_perfume_type_alter_longevity_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='type',
            field=models.CharField(choices=[('Perfume', 'perfume'), ('Attar', 'attar')], default='perfume', max_length=20),
        ),
    ]
